POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "abcd@test.com",
    "password": "12345"
}

### Signining in the user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "abcd@test.com",
    "password": "12345"
}

### Get the current sign in user
GET http://localhost:3000/auth/whoAmi

### Find a particular user with given id
GET http://localhost:3000/auth/1

### Find all users with given email.
GET http://localhost:3000/auth?email=abcd@asdf.com

### Delete user with a particular id
DELETE http://localhost:3000/auth/2

### Update user controller testing
PATCH http://localhost:3000/auth/3
content-type: application/json 

{
    "email": "bbbb@bbbb.com"
}